var annotated_dup =
[
    [ "Application", "classApplication.html", "classApplication" ],
    [ "BallComponent", "classBallComponent.html", null ],
    [ "BallSystem", "classBallSystem.html", "classBallSystem" ],
    [ "Collision", "structCollision.html", null ],
    [ "CollisionSystem", "classCollisionSystem.html", "classCollisionSystem" ],
    [ "Component", "classComponent.html", "classComponent" ],
    [ "ComponentArray", "classComponentArray.html", "classComponentArray" ],
    [ "ComponentManager", "classComponentManager.html", "classComponentManager" ],
    [ "CoordinateSystem", "structCoordinateSystem.html", null ],
    [ "Coordinator", "classCoordinator.html", null ],
    [ "EntityManager", "classEntityManager.html", "classEntityManager" ],
    [ "Gravity", "classGravity.html", null ],
    [ "IComponentArray", "classIComponentArray.html", null ],
    [ "Logger", "classLogger.html", null ],
    [ "LogTransform", "classLogTransform.html", "classLogTransform" ],
    [ "Paddle", "classPaddle.html", null ],
    [ "PaddleControls", "classPaddleControls.html", "classPaddleControls" ],
    [ "RectangleCollider", "classRectangleCollider.html", null ],
    [ "RenderSpriteSystem", "classRenderSpriteSystem.html", "classRenderSpriteSystem" ],
    [ "RocApplication", "classRocApplication.html", "classRocApplication" ],
    [ "RocketKeyboard", "structRocketKeyboard.html", null ],
    [ "RocTests", "classRocTests.html", "classRocTests" ],
    [ "Shader", "classShader.html", "classShader" ],
    [ "ShaderHashMap", "classShaderHashMap.html", "classShaderHashMap" ],
    [ "Shaders", "classShaders.html", null ],
    [ "Sprite", "classSprite.html", "classSprite" ],
    [ "System", "classSystem.html", "classSystem" ],
    [ "SystemManager", "classSystemManager.html", null ],
    [ "TexInfoHash", "classTexInfoHash.html", null ],
    [ "TextureHashMap", "classTextureHashMap.html", "classTextureHashMap" ],
    [ "TextureInfo", "structTextureInfo.html", "structTextureInfo" ],
    [ "Textures", "classTextures.html", null ],
    [ "Transform", "classTransform.html", null ]
];